substitutions:
  name: "athom-sw04"
  friendly_name: "Athom SW04"
  project_name: "athom.sw04"
  project_version: "1.1"
  light4_restore_mode: RESTORE_DEFAULT_OFF
  package_sw03: github://athom-tech/athom-configs/athom-sw03.yaml
  package_dashboard: github://athom-tech/athom-configs/athom-sw04.yaml

packages:
  athom.sw03: ${package_sw03}

dashboard_import:
  package_import_url: ${package_dashboard}

binary_sensor:
  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO16
    name: "${friendly_name} Button 4"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light4
    on_press:
      then:
      - logger.log: "pressed"
    on_release:
      then:
      - logger.log: "released"
    on_double_click:
      min_length: 100ms
      max_length: 1000ms
      then:
      - logger.log: "double clicked"

output:
  # Relays
  - platform: gpio
    pin: GPIO14
    id: relay4

light:
  # Relays
  - platform: binary
    name: "${friendly_name} Light 4"
    id: light4
    output: relay4
    restore_mode: ${light4_restore_mode}
