substitutions:
  name: "athom-sw02"
  friendly_name: "Athom SW02"
  project_name: "athom.sw02"
  project_version: "1.1"
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  package_sw01: github://athom-tech/athom-configs/athom-sw01.yaml
  package_dashboard: github://athom-tech/athom-configs/athom-sw02.yaml
  add_mac_suffix: true

packages:
  athom.sw01: ${package_sw01}

binary_sensor:
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "${friendly_name} Button 2"
    disabled_by_default: false
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

output:
  # Relays
  - platform: gpio
    pin: GPIO4
    id: relay2

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: led2

light:
  # Relays
  - platform: binary
    name: "${friendly_name} Light 2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    on_turn_on:
      - light.turn_on: light2
    on_turn_off:
      - light.turn_off: light2

  # Button LEDs
  - platform: monochromatic
    name: "${friendly_name} LED2"
    disabled_by_default: true
    id: light4
    output: led2
    default_transition_length: 500ms
