substitutions:
  name: "athom-sw03"
  friendly_name: "Athom SW03"
  project_name: "athom.sw03"
  project_version: "1.1"
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  package_sw02: github://athom-tech/athom-configs/athom-sw02.yaml
  package_dashboard: github://athom-tech/athom-configs/athom-sw03.yaml
  add_mac_suffix: true

packages:
  athom.sw02: ${package_sw02}

dashboard_import:
  package_import_url: ${package_dashboard}

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "${friendly_name} Button 3"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

output:
  # Relays
  - platform: gpio
    pin: GPIO15
    id: relay3

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: button_led3

light:
  # Relays
  - platform: binary
    name: "${friendly_name} Light 3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    on_turn_on:
      - light.turn_on: led3
    on_turn_off:
      - light.turn_off: led3

  # Button LEDs
  - platform: monochromatic
    name: "${friendly_name} LED3"
    disabled_by_default: true
    id: led3
    output: button_led3
    default_transition_length: 500ms
